from abc import ABC, abstractmethod
from uuid import UUID
from app.content.domain.entities import Article, Category, Tag


class ArticleRepository(ABC):
    @abstractmethod
    async def get_by_id(self, article_id: UUID) -> Article | None: ...
    @abstractmethod
    async def get_by_slug(self, slug: str) -> Article | None: ...
    @abstractmethod
    async def create(self, article: Article, tag_ids: list[UUID] | None = None) -> Article: ...
    @abstractmethod
    async def update(self, article: Article, tag_ids: list[UUID] | None = None) -> Article: ...
    @abstractmethod
    async def delete(self, article_id: UUID) -> None: ...
    @abstractmethod
    async def list_articles(self, page: int = 1, limit: int = 6, category_slug: str | None = None, tag_slug: str | None = None, search: str | None = None, author_id: UUID | None = None, featured: bool | None = None, status: str | None = None, sort: str = "published_at", order: str = "desc") -> tuple[list[dict], int]: ...
    @abstractmethod
    async def increment_views(self, article_id: UUID) -> int: ...
    @abstractmethod
    async def ensure_slug_unique(self, slug: str, exclude_id: UUID | None = None) -> str: ...


class CategoryRepository(ABC):
    @abstractmethod
    async def get_by_id(self, category_id: UUID) -> Category | None: ...
    @abstractmethod
    async def get_by_slug(self, slug: str) -> Category | None: ...
    @abstractmethod
    async def create(self, category: Category) -> Category: ...
    @abstractmethod
    async def update(self, category: Category) -> Category: ...
    @abstractmethod
    async def delete(self, category_id: UUID) -> None: ...
    @abstractmethod
    async def list_categories(self) -> list[Category]: ...
    @abstractmethod
    async def has_articles(self, category_id: UUID) -> bool: ...


class TagRepository(ABC):
    @abstractmethod
    async def get_by_id(self, tag_id: UUID) -> Tag | None: ...
    @abstractmethod
    async def get_by_slug(self, slug: str) -> Tag | None: ...
    @abstractmethod
    async def create(self, tag: Tag) -> Tag: ...
    @abstractmethod
    async def update(self, tag: Tag) -> Tag: ...
    @abstractmethod
    async def delete(self, tag_id: UUID) -> None: ...
    @abstractmethod
    async def list_tags(self, search: str | None = None, limit: int = 50) -> list[Tag]: ...
