from abc import ABC, abstractmethod
from uuid import UUID
from app.identity.domain.entities import User


class UserRepository(ABC):
    @abstractmethod
    async def get_by_id(self, user_id: UUID) -> User | None: ...
    @abstractmethod
    async def get_by_email(self, email: str) -> User | None: ...
    @abstractmethod
    async def create(self, user: User) -> User: ...
    @abstractmethod
    async def update(self, user: User) -> User: ...
    @abstractmethod
    async def list_users(self, page: int = 1, limit: int = 20, role: str | None = None, search: str | None = None, is_active: bool | None = None, sort: str = "created_at", order: str = "desc") -> tuple[list[User], int]: ...
    @abstractmethod
    async def update_last_login(self, user_id: UUID) -> None: ...
